version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "7070:70"
        volumes:
            - .:/app/
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/